on:
  push:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: Start-Process -FilePath 'C:/Program Files/Git/bin/sh.exe' -ArgumentList 'foo.t'
