on:
  push:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show CC
        run: $Env:CC
      - name: Test
        run: make -i test-create-process
      - name: Run create-process
        run: |
          & ./create-process.exe 'bash --version'
