on:
  push:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Direct
        continue-on-error: true
        run: bash foo.t
      - name: Build
        run: gcc create-process.c -o create-process
      - name: Run create-process
        continue-on-error: true
        run: ./create-process.exe 'bash foo.t' 2>&1
      - name: Make
        run: make test
