on:
  push:

jobs:
  test:
    continue-on-error: true
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: make
  test-windows:
    continue-on-error: true
    strategy:
      fail-fast: false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test with default
        run: make -i SHELL='C:/Program Files/Git/bin/sh.exe'
      - name: Test with default (no exe)
        run: make -i SHELL='C:/Program Files/Git/bin/sh'
      - name: Test with bash
        run: make -i SHELL='C:/Program Files/Git/usr/bin/bash.exe'
      - name: Test with bash (no exe)
        run: make -i SHELL='C:/Program Files/Git/usr/bin/bash'
